//
// Copyright (C) 2011-14 Irwin Zaid, DyND Developers
// BSD 2-Clause License, see LICENSE.txt
//

#ifndef _DYND__COMPARISION_HPP_
#define _DYND__COMPARISION_HPP_

#include <dynd/pp/gen.hpp>
#include <dynd/pp/list.hpp>
#include <dynd/pp/logical.hpp>

#define DYND_PP_LT(A, B) DYND_PP_CAT_4(DYND_PP_LT_, DYND_PP_BOOL(A), \
    _, DYND_PP_BOOL(B))(DYND_PP_GET(A, DYND_PP_SLICE_TO(B, DYND_PP_CAT_2(DYND_PP_ONES_, \
    DYND_PP_LEN_MAX)), DYND_PP_CAT_2(DYND_PP_ZEROS_, DYND_PP_LEN_MAX)))
#define DYND_PP_LT_0_0(...) 0
#define DYND_PP_LT_1_0(...) 0
#define DYND_PP_LT_0_1 DYND_PP_ID
#define DYND_PP_LT_1_1 DYND_PP_ID

#define DYND_PP_LE(A, B) DYND_PP_GE(B, A)

#define DYND_PP_EQ(A, B) DYND_PP_HAS_COMMA(DYND_PP_CAT_4(DYND_PP_EQ_, A, _, B))

#define DYND_PP_NE(A, B) DYND_PP_NOT(DYND_PP_EQ(A, B))

#define DYND_PP_GE(A, B) DYND_PP_CAT_4(DYND_PP_GE_, DYND_PP_BOOL(A), \
    _, DYND_PP_BOOL(B))(DYND_PP_GET(A, DYND_PP_SLICE_TO(B, DYND_PP_CAT_2(DYND_PP_ZEROS_, DYND_PP_LEN_MAX)), \
    DYND_PP_CAT_2(DYND_PP_ONES_, DYND_PP_LEN_MAX)))
#define DYND_PP_GE_0_0(...) 1
#define DYND_PP_GE_0_1 DYND_PP_ID
#define DYND_PP_GE_1_0(...) 1
#define DYND_PP_GE_1_1 DYND_PP_ID

#define DYND_PP_GT(A, B) DYND_PP_LT(B, A)

#define DYND_PP_ALL_LT(A, B) DYND_PP_ALL(DYND_PP_ELEMENTWISE(DYND_PP_LT, A, B))
#define DYND_PP_ANY_LT(A, B) DYND_PP_ANY(DYND_PP_ELEMENTWISE(DYND_PP_LT, A, B))

#define DYND_PP_ALL_LE(A, B) DYND_PP_ALL(DYND_PP_ELEMENTWISE(DYND_PP_LE, A, B))
#define DYND_PP_ANY_LE(A, B) DYND_PP_ANY(DYND_PP_ELEMENTWISE(DYND_PP_LE, A, B))

#define DYND_PP_ALL_EQ(A, B) DYND_PP_ALL(DYND_PP_ELEMENTWISE(DYND_PP_EQ, A, B))
#define DYND_PP_ANY_EQ(A, B) DYND_PP_ANY(DYND_PP_ELEMENTWISE(DYND_PP_EQ, A, B))

#define DYND_PP_ALL_NE(A, B) DYND_PP_ALL(DYND_PP_ELEMENTWISE(DYND_PP_NE, A, B))
#define DYND_PP_ANY_NE(A, B) DYND_PP_ANY(DYND_PP_ELEMENTWISE(DYND_PP_NE, A, B))

#define DYND_PP_ALL_GE(A, B) DYND_PP_ALL(DYND_PP_ELEMENTWISE(DYND_PP_GE, A, B))
#define DYND_PP_ANY_GE(A, B) DYND_PP_ANY(DYND_PP_ELEMENTWISE(DYND_PP_GE, A, B))

#define DYND_PP_ALL_GT(A, B) DYND_PP_ALL(DYND_PP_ELEMENTWISE(DYND_PP_GT, A, B))
#define DYND_PP_ANY_GT(A, B) DYND_PP_ANY(DYND_PP_ELEMENTWISE(DYND_PP_GT, A, B))

#endif
