//
// Copyright (C) 2011-14 Irwin Zaid, DyND Developers
// BSD 2-Clause License, see LICENSE.txt
//

#ifndef _DYND__PP_META_HPP_
#define _DYND__PP_META_HPP_

#define DYND_PP_META_EQ(LHS, RHS) LHS = RHS
#define DYND_PP_META_NE(LHS, RHS) LHS != RHS

#define DYND_PP_META_DECL(TYPE, VAR) TYPE VAR
#define DYND_PP_META_DECL_EQ(TYPE, VAR, VALUE) DYND_PP_META_EQ(DYND_PP_META_DECL(TYPE, VAR), VALUE)


#define DYND_PP_META_AT(VAR, INDEX) VAR[INDEX]

#define DYND_PP_META_CALL(FUNC) FUNC()

#define DYND_PP_META_DOT(LHS, RHS) LHS.RHS
#define DYND_PP_META_DOT_CALL(OBJ, FUNC) DYND_PP_META_DOT(OBJ, DYND_PP_META_CALL(FUNC))

#define DYND_PP_META_SCOPE(LHS, RHS) LHS::RHS
#define DYND_PP_META_SCOPE_CALL(OBJ, FUNC) DYND_PP_META_SCOPE(OBJ, DYND_PP_CALL(FUNC))

#define DYND_PP_META_TYPENAME(TYPE) typename TYPE

#endif
