#!/bin/sh

# This script is for launching cling (http://root.cern.ch/drupal/content/cling)
# with the dynamicndarray library included. It has not been tested recently,
# and likely doesn't work presently.

cling -std=c++0x -fexceptions -fcxx-exceptions -l ./libdynamicndarray.so -I ./include -l dnd/cling_all.hpp
